users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage/', mypage, name="mypage"),
    # follow url추가
    path('<int:id>/follow', follow, name="follow"),
]

users/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
# receiver와 post_save import 하기
from django.dispatch import receiver
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followings = models.ManyToManyField("self", related_name="followers", symmetrical=False)

# ↓ user생성 시 자동으로 profile이 생성되고 저장될 수 있도록 함 ↓
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render, redirect
from main.models import Post
from django.contrib.auth.models import User


def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    # 로그인한 유저이름과 글 작성자 이름이 동일한 글 필터링
    context = {
        'user' : user,
        'posts' : Post.objects.filter(writer=user),
        'followings': user.profile.followings.all(),
        'followers': user.profile.followers.all(),
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    * {
        text-align: center;
    }

    .container {
        margin-top: 5%;
        border: 3px solid #d4dbf3;
        border-radius: 15px;
        min-height: 70vh;
    }

    h1 {
        font-family: "Black Han Sans";
        color: brown;
        margin-top: 3%;
    }

    h3 {
        font-family: "AppleSDGothicNeoM";
        color: brown;
        margin: 2% 0;
    }

    input {
        width: 70%;
        height: 40px;
        border: 3px solid #d4dbf3;
        border-radius: 15px;
    }
</style>


<div class="container">
    <h1>
        <h1>사용자명: {{user.username}}</h1>
        {% if request.user != user %}<!--다른 사람의 프로필에 들어온 경우에만 팔로우/언팔로우 버튼이 보임-->
            {% if request.user.profile in user.profile.followers.all %}
                <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
            {% else %}
                <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
            {% endif %}
        {% endif %}
    </h1>


    <div class="container2">
        <h3>팔로워{{user.profile.followers.count}}명</h3>
        {% for follower in user.profile.followers.all %}
            <h4><a href="{% url 'users:mypage' follower.user.id %}">{{ follower.user.username }}</a></h4>
        {% endfor %}
<hr>
        <h3>팔로잉{{user.profile.followings.count}}명</h3>
        {% for following in user.profile.followings.all %}
            <h4><a href="{% url 'users:mypage' following.user.id %}">{{ following.user.username }}</a></h4>
        {% endfor %}
    </div>
    <br><hr>
    <div>
        <h3>{방명록 작성글 목록}</h3>
    {% for post in posts %}
        <div style="margin-bottom: 2%;">
            제목 : <a href="{% url 'main:detail' post.id %}"><input type="button" value="{{post.title}}"/></a>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}