main/urls.py
from django.urls import path
from .views import *
from .views import update_comment, delete_comment
# from . import views

app_name = "main"
urlpatterns = [
     path('', showmain, name="showmain"),
     path('writepage/', showwrite, name="showwrite"),
     path('photopage/', showphoto, name="showphoto"),
     path('mbti/', showmbti, name="showmbti"),
     path('edit/<int:id>', edit, name="edit"),
     path('update/<int:id>', update, name="update"),
     path('delete/<int:id>', delete, name="delete"),
     path('<str:id>', detail, name="detail"),
     path('posts/', posts, name="posts"),
     path('new/', new, name="new"),
     path('<int:post_id>/create_comment', create_comment, name="create_comment"),
     path('<str:post_id>/<str:comment_id>/update_comment', update_comment, name="update_comment"),
     path('<str:post_id>/<str:comment_id>/edit_comment', edit_comment, name="edit_comment"),

     # comment UD 시에는 post와 comment id 둘 다 필요
     path('<str:comment_id>/delete_comment',
          delete_comment, name="delete_comment"),

     # like, dislike toggle
     path('like_toggle/<int:post_id>/', like_toggle, name="like_toggle"),
     path('dislike_toggle/<int:post_id>/',
          dislike_toggle, name="dislike_toggle"),

     # 좋아요 목록
     path('my_like/<int:user_id>/', my_like, name="my_like"),
]

main/templates/main/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    * {
        text-align: center;
    }
</style>

<h1 style="font-family: 'AppleSDGothicNeoEB';">{{post.title}}</h1>
<div>
    {% if post.writer %}
    {% if 'user' in post.writer.username %}
        <h3 style="text-align: right; margin-right: 3%; font-family: AppleSDGothicNeoM;">작성자 : <a href="{% url 'users:mypage' post.writer.id %}"> {{ post.writer.last_name }} {{ post.writer.first_name }} </a></h3>
    {% else %}
        <h3 style="text-align: right; margin-right: 3%; font-family: AppleSDGothicNeoM;">작성자 : <a href="{% url 'users:mypage' post.writer.id %}"> {{ post.writer }} </a></h3>
    {% endif %}
{% else %}
        <h3 style="text-align: right; margin-right: 3%; font-family: AppleSDGothicNeoM;">작성자 : 알 수 없음</h3>
{% endif %}
    <div style="text-align: right; margin-right: 3%; font-family: AppleSDGothicNeoM;">
        날짜 : {{post.pub_date}}
    </div>
</div>

<hr>

{% if post.image %}
<p><img src="{{post.image.url}}" alt="사진" style="width: 400px; height: auto;"></p>
{% endif %}
<p style="font-family: AppleSDGothicNeoM; font-size: 24px;">{{post.body}}</p>


<div class="interaction_button" style="display: flex; flex-direction: row; justify-content:center;">
    <!-- 좋아요 버튼 -->
    <span href="#" class="like" name ="{{post.id}}" value="Like" style="margin-right: 3%;">
        {% if user in post.like_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-heart" id ="like-icon" style="color: red; font-size: 27px;"></i>
        </div>
        {% else %}
        <div class="alt-service-icon">
            <i class="far fa-heart" id ="like-icon" style="color: red; font-size: 27px;"></i>
        </div>
        {% endif %}
            <span id="count-{{ post.id }}" class="alt-services-title font-alt">
                Like
            {% if post.like_count == 0 %}
                0개
            {% else %}
                {{ post.like_count }}개
            {% endif %}
            </span>
    </span>

    <!-- 싫어요 버튼 -->
    <span href="#" class="dislike" name ="{{post.id}}" value="Dislike">
        {% if user in post.dislike_user_set.all %}
        <div class="alt-service-icon">
            <i class="fa-solid fa-heart-crack" id ="dislike-icon" style="color: blue; font-size: 27px;"></i>
        </div>
        {% else %}
        <div class="alt-service-icon">
            <i class="far fa-heart" id ="dislike-icon" style="color: blue; font-size: 27px;"></i>
        </div>
        {% endif %}
            <span id="count2-{{ post.id }}" class="alt-services-title font-alt">
                Dislike
            {% if post.dislike_count == 0 %}
                0개
            {% else %}
                {{ post.dislike_count }}개
            {% endif %}
            </span>
    </span>
</div>

<br>
{% if user == post.writer %}
    <a href="{% url 'main:edit' post.id %}"><input type="button" value="수정" style="margin-right: 1%; width: 100px; height: 35px;"></a>
    <a href="{% url 'main:delete' post.id %}"><input type="button" value="삭제" style="width: 100px; height: 35px;"></a>
{% endif %}

<br><hr>
<div>
    <form action="{%url 'main:create_comment' post.id%}" method="POST">
    {%csrf_token%}
    <div style="display: flex; flex-direction: row;">
        <textarea name="content" placeholder="댓글 입력" style="width: 90%; height: 75px; text-align: left; margin: 0 1%;"></textarea>
        <input type="submit" value="확인" style="width: 75px; height: 75px">
    </div>
    </form>
</div>

<br><br>
<hr>

<div>
    {% for comment in comments %}
        <div>
            작성자 : <a href="{% url 'users:mypage' comment.writer.id %}">{{comment.writer}}</a>
            {{comment.content}}
            
            {% if comment.comment_writer == writer %}
            {% comment %}
            <a href="{% url 'main:update_comment' comment.id %}"><input type="button" value="수정"></a> 
            {% endcomment %}
            {% if user == comment.writer %}
            <a href="{%url 'main:edit_comment' post.id comment.id%}"><input type="button" value="수정"></a>
            <a href="{%url 'main:delete_comment' comment.id%}"><input type="button" value="삭제"></a>
            {% endif %}
            <br><br>
            {% endif %}
            <!-- <p id="comment_time">댓글 작성시간 : {{comment.pub_date}}</p> -->
            <hr>
        </div>
    {% endfor %}
</div>

<h5><a href="{% url 'main:posts' %}"><input type="button" value="게시글 목록" style="width: 400px; height: 50px; background-color: #6e76d0; color: white; margin: 1% 0;"></a></h5>

<!-- 5. ajax 적용하기-->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk=$(this).attr('name')
        $.ajax({
            type:'POST',
            url:"{% url 'main:like_toggle' post.pk %}",
            data:{'pk':pk,'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:'json',
            success:function(response){
                if(response.like_count==null){
                    alert('로그인이 필요합니다.');
                    window.location.replace('/accounts/login/');
                }
                else{
                    if(response.result=='like'){
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart');
                    }
                    else{
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart');
                    }
                    $('#count-{{post.id}}').html('Like' + response.like_count + "개");
                }
            },
            error:function(request, status, error){
                alert("로그인이 필요합니다.")
                alert('code:'+request.status+'\n'+'message:'+request.responseText+"\n"+"error:"+error);
            },
        })
    })

    $(".dislike").click(function(){
        var pk=$(this).attr('name')
        $.ajax({
            type:'POST',
            url:"{% url 'main:dislike_toggle' post.pk %}",
            data:{'pk':pk,'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:'json',
            success:function(response){
                if(response.dislike_count==null){
                    alert('로그인이 필요합니다.');
                        window.location.replace('/accounts/login/');
                }
                else{
                    if(response.result=='dislike'){
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fa-solid fa-heart-crack');
                    }
                    else{
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-heart');
                    }
                    $('#count2-{{post.id}}').html('Dislike'+response.dislike_count+"개");
                }
            },
            error:function(request, status, error){
                alert("로그인이 필요합니다.")
                alert('code:'+request.status+'\n'+'message:'+request.responseText+"\n"+"error:"+error);
            },
        })
    })
</script>
{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    .container {
        display: flex;
        flex-direction: row;
        justify-content: center;
    }

    h1 {
        text-align: center;
        font-family: "AppleSDGothicNeoB";
        color: #6e76d0;
        margin-top: 5%;
    }

    p {
        font-size: 20px;
        font-family: "AppleSDGothicNeoLB";
    }

    input {
        width: 50vw;
        height: 50px;
        text-align: left;
        border-radius: 7px;
    }

    textarea {
        width: 50vw;
        text-align: left;
        border-radius: 7px;
    }

    .input-file-button {
        padding: 6px 25px;
        background-color:#6e76d0;
        border-radius: 4px;
        color: white;
        cursor: pointer;
    }

    button {
        width: 40vw;
        height: 50px;
        padding: 6px 25px;
        background-color:#6e76d0;
        border: none;
        border-radius: 4px;
        color: white;
        font-size: 20px;
        position: absolute;
        left: 30%;
    }
</style>

<h1>글 수정하기</h1>
<div class="container">
    <form action="{% url 'main:update' post.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
        <!-- <p>작성자 : <input type="text" name="writer" value="{{post.writer}}"></p> -->
        <p>사진 : <label class="input-file-button" for="input_file">업로드<input type="file" id="input_file" name="image" value="{{post.image}}" style="display: none;"></label></p>
        <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10" placeholder="수정하실 내용을 입력해주세요.">{{post.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>
{% endblock %}

main/templates/main/mbti.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mbti.css' %}?after">

<div class="mbti_grid">
    <div class="mbti_item" id="mbti_it1">
        <img src="{% static 'images/mbti.png' %}" class="mbti" alt="mbti"/>
    </div>
    <div class="mbti_item" id="mbti_it2">
        <ul>
            <li>"자유로운 영혼의 소유자"</li>
            <li>한번 삘 꽂히면 끝까지 함</li>
            <li>그 삘이 안 꽂히면 나태해짐</li>
            <li>하고 싶은게 많음</li>
            <li>완벽주의 성향</li>
        </ul>
    </div>
    <div class="mbti_item" id="mbti_it3">
        <h1 style="background-color: white;">CONTACT</h1>
        <a target="_blank" href="https://www.instagram.com/way_to_focus/?hl=ko"><img src="{% static 'images/instagram.jpg' %}" alt="Instagram" style="width: 100px; height:100px"></a>
        <br><br>
        Call : 010-9153-6965
        <br>
        E-mail : wnstj701@naver.com
        <br>    
    </div>
</div>

{% endblock %}

main/templates/main/my_like.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .card {
        box-shadow: 5px 7px 20px 0px rgb(156, 156, 156);
    }
</style>

    <div class="container">
        <p style="font-weight:bold;">🐳 내 좋아요 목록 🐳</p>
        <div class="row">
            {% for like in like_list %}
                <div class="col-md-3 col-6 item_list__card">
                    <div class="card">
                        {% if like.post.image %}
                            <a href="#">
                                <img src="{{ like.post.image.url }}" width="100%" height="100%" alt="...">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">{{ like.post.title }}</h5>
                                <a href="{% url 'main:detail' like.post.pk %}" class="btn btn-outline-primary">보러가기</a>
                            </div>
                        {% else %}
                            <div class="card-body">
                                <h5 class="card-title">{{ like.post.title }}</h5>
                                <a href="{% url 'main:detail' like.post.pk %}" class="btn btn-outline-primary">보러가기</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

main/templates/main/new.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    .container {
        display: flex;
        flex-direction: row;
        justify-content: center;
    }
    
    p {
        font-size: 20px;
        font-family: "AppleSDGothicNeoLB";
    }

    form {
        position: relative;
        top: 6vh;
    }

    input {
        width: 50vw;
        height: 50px;
        text-align: left;
        border-radius: 7px;
    }

    .input-file-button{
        padding: 6px 25px;
        background-color:#6e76d0;
        border-radius: 4px;
        color: white;
        cursor: pointer;
    }

    textarea {
        width: 50vw;
        text-align: left;
        border-radius: 7px;
    }

    button {
        width: 40vw;
        height: 50px;
        padding: 6px 25px;
        background-color:#6e76d0;
        border: none;
        border-radius: 4px;
        color: white;
        font-size: 20px;
        position: absolute;
        left: 10%;
    }

    h1 {
        text-align: center;
        font-family: "AppleSDGothicNeoB";
        color: #6e76d0;
        margin-top: 5%;
    }
</style>

<h1>방명록 작성</h1>
<div class="container">
    <form action="{%url 'create'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" placeholder=" 제목을 입력해주세요."></p>
        <!-- <p>작성자 : <input type="text" name="writer"></p> -->
        <p>사진 : <label class="input-file-button" for="input_file">업로드<input type="file" id="input_file" name="image" style="display:none;"></label></p>
        <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10" placeholder=" 준서에게 하고 싶은 말을 입력해주세요."></textarea></p>
        <button type="submit">등록</button>
    </form>
</div>

{% endblock %}

main/templates/main/photopage.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<img class="mypic" src="{% static 'images/Fancy.jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/riding.jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/lostmyway.jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (1).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (2).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (3).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (4).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (5).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (6).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (7).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (8).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (9).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (10).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (11).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (12).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (13).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (14).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (15).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (16).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (17).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (18).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (19).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (20).jpg' %}" alt="mypic"/>
<img class="mypic" src="{% static 'images/photo (21).jpg' %}" alt="mypic"/>


{% endblock %}

main/templates/main/posts.html
{% extends 'base.html' %}
{% load static %}
    
{% block content %}
<style>
    #list_main {
        text-align: center;
        font-family: "AppleSDGothicNeoB";
        color: #6e76d0;
    }
    
    .container {
        width: 1000px;
        border: 7px solid #7d83cd;
        border-radius: 20px;
        margin-bottom: 3%;
    }
    
    .container a{
        text-decoration: none;
        color: #494949;
    }
    
    .list_wrap h1 {
        font-family: "AppleSDGothicNeoM";
    }

    .list_wrap p {
        text-align: right;
    }
</style>


<br>
    {% if user.is_authenticated %}
        <h1 id="list_main">방명록</h1><br>
        <div class="container">
        {% for post in posts %}
            <a href="{% url 'main:detail' post.id %}">
                <div class="row">
                    <div class="list_wrap">
                        <h1>{{post.title}}</h1>
                        {% if post.writer %}
                        {% if 'user' in post.writer.username %}
                            <p>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</p>
                        {% else %}
                            <p>작성자 : {{ post.writer }}</p>
                        {% endif %}
                        {% else %}
                            <p>작성자 : 알 수 없음</p>
                        {% endif %}
                        
                        {{post.summary}}
                            <br><br>
                            <!-- <a href="{% url 'main:detail' post.id %}"><input type="button" value="더보기"/></a> -->
                            <hr>
                    </div>
                </div>
            </a>
            
    {% endfor %}
        </div>
    {% else %}
        <div>
            <a href="{% url 'account_login'%}" class="btn btn-warning">로그인</a>
            <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
        </div>
    {% endif %}

{% endblock %}

main/templates/main/show.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <section class="landing">
        <a href="https://github.com/AsherOh" target="_blank"><img src="{% static 'images/lion.png' %}" class="likelion" alt="likelion"/></a>
        <h1>Hello, LION</h1>
        <!-- <div class="searchbar">
            <form action="https://search.google.com/search">
                <div class="search">
                    <input type="text" name="query" value="" placeholder="아기사자 검색">
                    <button type="submit">검색</button>
                </div>
            </form>
        </div> -->
        <div class="arrow">
            <a href="#it1"><span></span><span></span><span></span></a>
        </div>
    </section>

    <!-- 최상단 이동 버튼 -->
    <input class="goupbtn" type="button" value="Top" onclick="clickme()">
    <script>
        function clickme() {
            window.scrollTo({top:0, left:0, behavior:'smooth'});
        }
    </script>

    <section class="landing_body">
        <div class="ld_container">
            <div class="item" id="it1">
                <p>멋쟁이사자처럼 10기 프론트엔드 아기사자 소개 페이지에 오신 것을 환영합니다.</p>
            </div>
            
            <div class="item" id="it2">
                <button id="btn_itd" onclick="showIntroduction()">Who Am I?</button>
                <script>
                    function showIntroduction() {
                        // 토글할 버튼 선택
                        const buttonClick = document.getElementById("it3");
                        // Introduction 보이기
                        if(buttonClick.style.display !== 'none') {
                            buttonClick.style.display = 'none';
                        }
                        // Introduction 숨기기
                        else {
                            buttonClick.style.display = 'block';
                        }
                    }
                </script>
            </div>
            <div class="item" id="it3" style="display: none;">
                <p>
                &ldquo;
                <br>
                여행, 사진, 그리고 책까지 구속되지 않고 자유롭지만,
                <br>
                실체가 보이지 않는 비로소 온전히 자신의 시간에 집중할 수 있는 것들을 좋아합니다.
                <br>
                때로는 치열하게, 때로는 그 누구보다 느리고 여유롭게 살기 위해 노력합니다.
                <br>
                하고 싶은 것을 기어코 성취했을 때의 보람과 성취,
                <br>
                모든 것을 내려놓고 오로지 그 시간을 만끽할 수 있는 그사이 어딘가의 균형 잡힌 삶을 추구합니다.
                <br>
                SNS로는 다하지 못하는 제 생각과 표현을
                <br>
                기록하고 싶어서 웹사이트를 개설하게 되었습니다.
                <br>
                잠깐 가면을 내려놓고,
                <br>
                온전한 자신 그대로를 맞이할 수 있는 시간이 되기를 희망합니다.
                <br>
                저는
                <br>
                나름의 자유와 낭만을 찾아
                <br>
                여행과 사진, 책과 함께 살아가고픈 여행자입니다,
                <br>
                반갑습니다.
                <br>
                &rdquo;
                <div class="v-line"></div>
                </p>
            </div>
            <div class="item" id="it4">
                <button id="btn_itd2" onclick="showAboutMe()">About Me</button>
            </div>
            <div class="item" id="it5">
                <h2>이력</h2>
                <ul>
                    <li>창원중앙고등학교 졸업</li>
                    <li>동국대학교 융합에너지신소재공학과 17학번</li>
                    <li>동국대학교 공학교육혁신센터 DAVINCI 5기</li>
                    <li>동국대학교 사진 소모임 네모믜꿈 전 회장</li>
                    <li>수도방위사령부 제1경비단 AOC 방공작전통제반 만기전역</li>
                    <li>동국대학교 러닝크루 D:Part 활동 중 무릎 부상</li>
                    <li>데이원 독서모임 4기 활동 中</li>
                </ul>
            </div>
            <div class="item" id="it6">
                <h2>대외활동</h2>
                <ul>
                    <li>비즈니스 협상전략 교육 수료</li>
                    <li>[폴앤마크] Tech-Business Innovation Camp 수료</li>
                    <li>오픈소스 플랫폼(Arduino) 활용 IoT 시스템 구현 교육 수료</li>
                    <li>공학페스티벌 공대생 심사위원단 E^2 Panel 활동</li>
                    <li>DoDream 고체재료화학 학습동아리 수료</li>
                    <li>[San José State Univ] Silicon Valley Innovation & Startup Program 수료</li>
                    <li>멋쟁이사자처럼 심바톤 수료</li>
                </ul>
            </div>
            <div class="item" id="it7">
                <h2>목표</h2>
                <ul>
                    <li>10기 중앙 해커톤 순위권 수상</li>
                    <li>주 4회 이상 독서 서평 기록</li>
                    <li>주 2회 이상 러닝</li>
                    <li>월 2회 이상 풋살</li>
                    <li>주 1회 이상 블로그 일기 작성</li>
                    <li>월 1회 이상 웹 프로그래밍 프로젝트</li>
                    <li>2023 예비창업패키지 선정</li>
                </ul>
            </div>
            <div class="item" id="it8">
                <button id="btn_itd3" onclick="showHobby()">Hobby</button>
            </div>
            <div class="item" id="it9">
                <img src="{% static 'images/photo.jpg' %}" class="photoMe" alt="photoMe"/>
                <span>"Photography"</span>
            </div>
            <div class="item" id="it10">
                <span>"Football"</span>
                <img src="{% static 'images/football.jpg' %}" class="football" alt="football"/>
            </div>
            <div class="item" id="it11">
                <img src="{% static 'images/riding.jpg' %}" class="riding" alt="riding"/>
                <span>"Cycling"</span>
            </div>
            <div class="item" id="it12">
                <button id="btn_itd4" onclick="location.href='mbti/'">What's my MBTI?</button>
                <script>

                </script>
            </div>
            <div class="item" id="it13">
                <h1>CONTACT</h1>
                <a target="_blank" href="https://www.instagram.com/way_to_focus/?hl=ko"><img src="{% static 'images/instagram.jpg' %}" alt="Instagram" style="width: 100px; height:100px"></a>
                <br><br>
                Call : 010-9153-6965
                <br>
                E-mail : wnstj701@naver.com
                <br>    
            </div>
        </div>
    </section>

    <!-- <footer>
        <div class="landing_btm">
            <h2>Contact</h2>
            <a target="blank" href="https://www.instagram.com/way_to_focus/?hl=ko"><img src="{% static 'images/instagram.jpg' %}" alt="Instagram" style="width: 100px; height:100px"></a>
            <br>
            <span>Call : 010-9153-6965</span>
            <br>
            <span>E-mail : wnstj701@naver.com</span>
            <br>
        </div>
    </footer> -->

{% endblock %}